[package]
name = "icp_token_wallet"
version = "0.1.0"
edition = "2018"

[dependencies]
ic-cdk = "0.5.0"
ic-cdk-macros = "0.5.0"
serde = "1.0"
serde_json = "1.0"
serde_cbor = "0.11"
candid = "0.7.4"

[lib]
crate-type = ["cdylib"]
